version: '3.0'
services:
  postgresql:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=technical-task
    ports:
      - "5432:5432"